### ISSUE TITLE
application/atom+xml

### ISSUE THREAD

**Issue by j0kk4r** [sanmai/cdek-sdk#105] opened 2021-02-19 12:49 UTC
https://github.com/sanmai/cdek-sdk/blob/c16ae66e2de093d176d9802b8d4418d22fb46fab/src/CdekClient.php#L330

Need Code:
`if (0 === \strpos($header, 'application/atom+xml')) {
            return true;
        }`

**Comment by sanmai** [comment] 2021-02-19 13:30
Duplicate of #103

**Closed by sanmai** 2021-02-19 13:31 UTC
